// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqN6dVUZ4vLAqovXgXvTmbjn1nFk-iCgA',
    appId: '1:590081848569:web:4c4e5a1715b80244a41e28',
    messagingSenderId: '590081848569',
    projectId: 'hotelapp-737c2',
    authDomain: 'hotelapp-737c2.firebaseapp.com',
    storageBucket: 'hotelapp-737c2.firebasestorage.app',
    measurementId: 'G-VSNQC2MKM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTvr0Mu5eKtVPIYpz8qV0IBYzSwOSk7lI',
    appId: '1:590081848569:android:006be2e829cddf3ca41e28',
    messagingSenderId: '590081848569',
    projectId: 'hotelapp-737c2',
    storageBucket: 'hotelapp-737c2.firebasestorage.app',
  );
}