// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcZpjMm3Bjlb9BWe-tL1M0UuxmqWE8_1k',
    appId: '1:884652939207:web:b59984bd5f8d015f9e2be2',
    messagingSenderId: '884652939207',
    projectId: 'aurelia-grand-hotel-7a102',
    authDomain: 'aurelia-grand-hotel-7a102.firebaseapp.com',
    storageBucket: 'aurelia-grand-hotel-7a102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfu0wcD6SIs2DTX_wiof8WbsZlxXnHxc',
    appId: '1:884652939207:android:b8328817143c3c7b9e2be2',
    messagingSenderId: '884652939207',
    projectId: 'aurelia-grand-hotel-7a102',
    storageBucket: 'aurelia-grand-hotel-7a102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeS1_zg-G4Aw5d7DdTrlvPdXVf23MFXU',
    appId: '1:884652939207:ios:a70d1a53436e206c9e2be2',
    messagingSenderId: '884652939207',
    projectId: 'aurelia-grand-hotel-7a102',
    storageBucket: 'aurelia-grand-hotel-7a102.firebasestorage.app',
    iosBundleId: 'com.example.hotelManageementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoeS1_zg-G4Aw5d7DdTrlvPdXVf23MFXU',
    appId: '1:884652939207:ios:a70d1a53436e206c9e2be2',
    messagingSenderId: '884652939207',
    projectId: 'aurelia-grand-hotel-7a102',
    storageBucket: 'aurelia-grand-hotel-7a102.firebasestorage.app',
    iosBundleId: 'com.example.hotelManageementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcZpjMm3Bjlb9BWe-tL1M0UuxmqWE8_1k',
    appId: '1:884652939207:web:2c5177c3fa3c75029e2be2',
    messagingSenderId: '884652939207',
    projectId: 'aurelia-grand-hotel-7a102',
    authDomain: 'aurelia-grand-hotel-7a102.firebaseapp.com',
    storageBucket: 'aurelia-grand-hotel-7a102.firebasestorage.app',
  );
}
